POST http://localhost:8082/v1/carts
Content-Type: application/json

{
  "name": "Today",
  "cartItemDBS": [
    {
      "name" : "Flour",
      "id": "1",
      "prodId": "70b7b4bf-d18e-48d9-bb74-fd317752eaac",
      "recipes": [
          "985f9f6f-c1de-4ef9-b320-8c7253cfdda3"
      ],
      "selected": false
    },
    {
      "name": "Sugar",
      "prodId": "b2427e3f-1bfb-40df-be32-92a7328710d5",
      "recipes": [
        "72aa50bb-fa27-4d7a-8b04-88608c121f3a"
      ],
      "selected": false
    }
  ]
}
> {% client.global.set("cartId",  response.body.id);  %}

<> 2020-07-08T115408.500.json
<> 2020-07-08T060014.200.json
<> 2020-07-08T055831.500.json
<> 2020-07-08T055335.500.json

###

PUT http://localhost:8082/v1/carts
Content-Type: application/json

{
  "id":  "{{cartId}}",
  "name": "Yesterday",
  "cartItemDBS": [
    {
      "id": "bc1fb4c8-0c32-44e0-b164-4872d7ce0ff3",
      "prodId": "001_p",
      "recipes": ["985f9f6f-c1de-4ef9-b320-8c7253cfdda3"],
      "selected": false
    }
  ]
}




