DROP TABLE IF EXISTS CATEGORY;
CREATE TABLE IF NOT EXISTS CATEGORY (
  id VARCHAR(50) PRIMARY KEY,
  NAME VARCHAR(50),
);

DROP TABLE IF EXISTS PRODUCT;
CREATE TABLE IF NOT EXISTS PRODUCT (
  id VARCHAR(50) PRIMARY KEY,
  NAME VARCHAR(50),
  CAT_ID VARCHAR(50),
  FOREIGN KEY (CAT_ID)
    REFERENCES CATEGORY(id)
);


DROP TABLE IF EXISTS RECIPE;
CREATE TABLE IF NOT EXISTS RECIPE (
  id VARCHAR(50) PRIMARY KEY,
  NAME VARCHAR(50),
);

DROP TABLE IF EXISTS PRODUCT_ITEM;
CREATE TABLE IF NOT EXISTS PRODUCT_ITEM (
  id VARCHAR(50) PRIMARY KEY,
  NAME VARCHAR(50),
  PROD_ID VARCHAR(50),
  FOREIGN KEY (PROD_ID)
    REFERENCES PRODUCT(id)
);

